name: Generate Snake Animation

on:
  schedule:
    # every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: adisonket
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Commit and Push the Snake SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "🐍 Generate Snake animation"
          add: "./output/github-contribution-grid-snake.svg"
